"""Add database indexes for performance

Revision ID: 164e848ccb00
Revises: 18e2f473a7a5
Create Date: 2026-05-13 14:12:48.999791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '164e848ccb00'
down_revision: Union[str, Sequence[str], None] = '18e2f473a7a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_room_name'), 'room', ['name'], unique=False)
    op.create_index(op.f('ix_task_dispatched_at'), 'task', ['dispatched_at'], unique=False)
    op.create_index(op.f('ix_task_room_id'), 'task', ['room_id'], unique=False)
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_index(op.f('ix_task_room_id'), table_name='task')
    op.drop_index(op.f('ix_task_dispatched_at'), table_name='task')
    op.drop_index(op.f('ix_room_name'), table_name='room')
    # ### end Alembic commands ###
