"""grid_map_and_tasks_init

Revision ID: 2aeafe74e43d
Revises: 
Create Date: 2026-05-18 20:34:53.218861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '2aeafe74e43d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x_coord', sa.Integer(), nullable=False),
    sa.Column('y_coord', sa.Integer(), nullable=False),
    sa.Column('node_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_occupied', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_node_type'), 'node', ['node_type'], unique=False)
    op.create_table('edge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Integer(), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source'], ['node.id'], ),
    sa.ForeignKeyConstraint(['target'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edge_source'), 'edge', ['source'], unique=False)
    op.create_index(op.f('ix_edge_target'), 'edge', ['target'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_dispatched_at'), 'task', ['dispatched_at'], unique=False)
    op.create_index(op.f('ix_task_node_id'), 'task', ['node_id'], unique=False)
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    op.create_table('robot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_node_id', sa.Integer(), nullable=False),
    sa.Column('current_task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_node_id'], ['node.id'], ),
    sa.ForeignKeyConstraint(['current_task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('robot')
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_index(op.f('ix_task_node_id'), table_name='task')
    op.drop_index(op.f('ix_task_dispatched_at'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_edge_target'), table_name='edge')
    op.drop_index(op.f('ix_edge_source'), table_name='edge')
    op.drop_table('edge')
    op.drop_index(op.f('ix_node_node_type'), table_name='node')
    op.drop_table('node')
    # ### end Alembic commands ###
