"""Add heading to robot

Revision ID: 40a17b658b00
Revises: 2aeafe74e43d
Create Date: 2026-05-31 22:01:35.329284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '40a17b658b00'
down_revision: Union[str, Sequence[str], None] = '2aeafe74e43d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robot', sa.Column('current_heading', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('robot', 'current_heading')
    # ### end Alembic commands ###
